name:                arbor-postgres
version:             0.0.1
github:              "arbor/arbor-postgres"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/arbor/arbor-postgres#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base                  >= 4.7      && < 5
- generic-lens          >= 1.0.0.2  && < 2
- lens                  >= 4.16     && < 5
- network-uri           >= 2.6      && < 3
- optparse-applicative  >= 0.14     && < 0.15
- postgresql-simple     >= 0.5      && < 0.6
- text                  >= 1.2      && < 1.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
