name:                arbor-postgres
version:             0.0.1
github:              "packetloop/arbor-postgres"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/packetloop/arbor-postgres#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base >=4.7 && <5
- generic-lens
- lens
- optparse-applicative
- postgresql-simple
- text

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
