resolver: lts-10.10

packages:
- .
- location:
    git: git@github.com:arbor/antiope.git
    commit: 775891bc3d6a7622e8c36bfc4e2dd857fbc84223
    subdirs:
      - antiope-core
      - antiope-s3
      - antiope-sqs
      - antiope-dynamodb
  extra-dep: true

extra-deps:
  - avro-0.2.0.0
  - bits-extra-0.0.0.2
  - concurrent-extra-0.7.0.11
  - hedgehog-0.5.2
  - hw-balancedparens-0.2.0.1
  - hw-bits-0.7.0.2
  - hw-conduit-0.2.0.3
  - hw-excess-0.2.0.0
  - hw-fingertree-strict-0.1.0.3
  - hw-hspec-hedgehog-0.1.0.1
  - hw-int-0.0.0.1
  - hw-kafka-avro-1.3.0
  - hw-kafka-client-2.3.3
  - hw-kafka-conduit-2.0.0
  - hw-parser-0.0.0.2
  - hw-prim-0.5.0.3
  - hw-rankselect-0.12.0.0
  - hw-rankselect-base-0.3.0.0
  - hw-xml-0.1.0.3
  - lazy-csv-0.5.1
  - megaparsec-4.4.0
  - optparse-applicative-0.14.0.0
  - pure-zlib-0.6
  - temporary-resourcet-0.1.0.0
  - text-short-0.1.2
