version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.2
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.3.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2
          context: haskell-ci
          binary-cache-uri: s3://hw-binary-cache-us-west-2/archive-abc

      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: s3://hw-binary-cache-us-west-2/archive-abc

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: s3://hw-binary-cache-us-west-2/archive-abc

      - haskell/build-with-binary-cache:
          name: GHC 8.8.1
          executor: haskell/ghc-8_8_1
          context: haskell-ci
          binary-cache-uri: s3://hw-binary-cache-us-west-2/archive-abc

      - github/release-cabal:
          name: GitHub Release
          requires:
            - GHC 8.2.2
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.1
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          filters:
            branches:
              only: master
